// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlsy1lUaTxB9Wg9MdRmZLFkqOO2TDV3cw',
    appId: '1:221732241493:web:c2150cdeda9774a13b54dc',
    messagingSenderId: '221732241493',
    projectId: 'chatting-fc27f',
    authDomain: 'chatting-fc27f.firebaseapp.com',
    storageBucket: 'chatting-fc27f.appspot.com',
    measurementId: 'G-9ZT1C9RXE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtgHhXEwXqiBpsMQbK5Lj4-Avuuao7uEo',
    appId: '1:221732241493:android:dc185421d4fbe7523b54dc',
    messagingSenderId: '221732241493',
    projectId: 'chatting-fc27f',
    storageBucket: 'chatting-fc27f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO_j-IFD2tLRnuLxeErLgVfL4ywS9fXDs',
    appId: '1:221732241493:ios:c81c559408e559f73b54dc',
    messagingSenderId: '221732241493',
    projectId: 'chatting-fc27f',
    storageBucket: 'chatting-fc27f.appspot.com',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO_j-IFD2tLRnuLxeErLgVfL4ywS9fXDs',
    appId: '1:221732241493:ios:c81c559408e559f73b54dc',
    messagingSenderId: '221732241493',
    projectId: 'chatting-fc27f',
    storageBucket: 'chatting-fc27f.appspot.com',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlsy1lUaTxB9Wg9MdRmZLFkqOO2TDV3cw',
    appId: '1:221732241493:web:cb3c92c04135dba03b54dc',
    messagingSenderId: '221732241493',
    projectId: 'chatting-fc27f',
    authDomain: 'chatting-fc27f.firebaseapp.com',
    storageBucket: 'chatting-fc27f.appspot.com',
    measurementId: 'G-Z1CXJSNPCP',
  );
}
